### ISSUE TITLE
[Request] Populate last modified date per topic from `history`

### ISSUE THREAD

**Issue by kushnir-v** [shapiy/charon#3]
### Request
Populate the Last-Modified date (if any exists) in HTML head/meta in ISO format.

### Expected result
 `<meta name="revisedDate" content="2020-01-10T18:02:25.352Z"></meta>` (same)

**Comment by shapiy** [comment]
Lot's of new metadata related to Confluence `lastUpdated` are now (8b1749848b900eb1b69aefa8c663ef590d9dfebc) being populated.

```
<meta name="lastUpdated.when" content="2020-05-06T15:29:05.351Z">
```
